### PR TITLE
Skeles AE2 recipes

### PR DESCRIPTION
**Pull request by Strikingwolf**
If these are stable it would be nice to have them in

### CODE REVIEW

**Comment by Strikingwolf** [comment]
This needs to be closed

**Comment by Gideonseymour** [comment]
lol

**Comment by SkeletonPunk** [comment]
I should really update this.

**Comment by trajing** [comment]
DAMMIT USE THE PT REPO

**Comment by SkeletonPunk** [comment]
Lel

**Comment by Elec332** [comment]
Just delete this one

**Pull request closed without merging**
